parSet{1}     = {'spine', 'apicalTuft'   , 'terminal'                       , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apicalOblique', 'terminal'                       , 1e-6, [-1 0 1]};
%parSet{end+1} = {'spine', 'apicalTrunk'  , 'terminal'                       , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apical'       , 'terminal'                       , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'basal'        , 'terminal'                       , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apicalTuft'   , 'intermediate'                   , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apicalOblique', 'intermediate'                   , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apicalTrunk'  , 'intermediate'                   , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apical'       , 'intermediate'                   , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'basal'        , 'intermediate'                   , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apicalTuft'   , 'intermediateOrTerminal'         , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apicalOblique', 'intermediateOrTerminal'         , 1e-6, [-1 0 1]};
%parSet{end+1} = {'spine', 'apicalTrunk'  , 'intermediateOrTerminal'         , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apical'       , 'intermediateOrTerminal'         , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'basal'        , 'intermediateOrTerminal'         , 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apicalTuft'   , 'primaryOrIntermediateOrTerminal', 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apicalOblique', 'primaryOrIntermediateOrTerminal', 1e-6, [-1 0 1]};
%parSet{end+1} = {'spine', 'apicalTrunk'  , 'primaryOrIntermediateOrTerminal', 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'apical'       , 'primaryOrIntermediateOrTerminal', 1e-6, [-1 0 1]};
parSet{end+1} = {'spine', 'basal'        , 'primaryOrIntermediateOrTerminal', 1e-6, [-1 0 1]};
parSet{end+1} = {'IS'   , 'apicalTuft'   , 'terminal'                       , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apicalOblique', 'terminal'                       , 1e-6, [0 1]};
%parSet{end+1} = {'IS'   , 'apicalTrunk'  , 'terminal'                       , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apical'       , 'terminal'                       , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'basal'        , 'terminal'                       , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apicalTuft'   , 'intermediate'                   , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apicalOblique', 'intermediate'                   , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apicalTrunk'  , 'intermediate'                   , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apical'       , 'intermediate'                   , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'basal'        , 'intermediate'                   , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apicalTuft'   , 'intermediateOrTerminal'         , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apicalOblique', 'intermediateOrTerminal'         , 1e-6, [0 1]};
%parSet{end+1} = {'IS'   , 'apicalTrunk'  , 'intermediateOrTerminal'         , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apical'       , 'intermediateOrTerminal'         , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'basal'        , 'intermediateOrTerminal'         , 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apicalTuft'   , 'primaryOrIntermediateOrTerminal', 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apicalOblique', 'primaryOrIntermediateOrTerminal', 1e-6, [0 1]};
%parSet{end+1} = {'IS'   , 'apicalTrunk'  , 'primaryOrIntermediateOrTerminal', 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'apical'       , 'primaryOrIntermediateOrTerminal', 1e-6, [0 1]};
parSet{end+1} = {'IS'   , 'basal'        , 'primaryOrIntermediateOrTerminal', 1e-6, [0 1]};

for pS=1:numel(parSet)
  disp([parSet{pS}{1} ', ' parSet{pS}{2} ', ' parSet{pS}{3}]);
  featureDensityTest(parSet{pS}{1}, parSet{pS}{2}, parSet{pS}{3}, parSet{pS}{4}, parSet{pS}{5}, 5, 10000);
end
